rclone purge "dropbox:Dropbox Fanny/_PhD/dataset/RNASeq"
rclone purge "dropbox:Dropbox Fanny/_PhD/dataset/RNASeqV2"
rclone purge "dropbox:Dropbox Fanny/Sauvegarde/Sauvegarde vieil ordi/Documents/Documents/R"
rclone purge "dropbox:Dropbox Fanny/Sauvegarde/Sauvegarde vieil ordi/Documents/Documents/MATLAB"
rclone purge "dropbox:Dropbox Fanny/Sauvegarde/Sauvegarde vieil ordi/Documents/Documents/src"
rclone purge "dropbox:Dropbox Fanny/Sauvegarde/Sauvegarde vieil ordi/Documents/Documents/cyt-vz"
rclone purge "dropbox:Dropbox Fanny/Sauvegarde/Sauvegarde vieil ordi/Documents/Documents/cyt3-windows"
rclone purge "dropbox:Dropbox Fanny/_PhD/CyTOF"
rclone purge "dropbox:Dropbox Fanny/_PhD/IF"
rclone purge "dropbox:Dropbox Fanny/_PhD/MATLAB"
rclone purge "dropbox:Dropbox Fanny/_PhD/Mice"
rclone purge "dropbox:Dropbox Fanny/PhD/The Ladies Paper"
rclone purge "dropbox:Dropbox Fanny/PhD/131209 Mammary glands"